SET INPUT_ENVNAME=acn_stdemo
SET INPUT_PACKAGE=force-di
SET INPUT_PACKAGEINSTALLEDFROM=Custom
SET INPUT_PACKAGE_VERSION_ID=04t1P000000VXMYQA4
SET INPUT_apexcompileonlypackage=true
SET INPUT_SECURITY_TYPE=AllUsers
SET INPUT_UPGRADE_TYPE=Mixed
SET INPUT_WAIT_TIME=120
SET INPUT_PUBLISH_WAIT_TIME=10





ts-node ..\..\BuildTasks\InstallUnlockedPackageTask\InstallUnlockedPackage.ts

