
SET INPUT_TARGET_ORG=acn_stdemo
SET INPUT_ISMANAGEDPACKAGECOMPONENTSTOBEEXCLUDED=true
SET INPUT_SOURCE_DIRECTORY=force-di
SET INPUT_ISUNZIPENABLED=true
SET INPUT_ISTELEMETRYENABLED=false






ts-node ..\..\BuildTasks\ExportSourceFromAnOrgTask\ExportSourceFromAnOrg.ts

