SET INPUT_PACKAGE=force-di
SET INPUT_VERSION_NUMBER=
SET INPUT_TAG=master
SET INPUT_CONFIG_FILE_PATH=config\project-scratch-def.json
SET INPUT_INSTALLATIONKEYBYPASS=true
SET INPUT_INSTALLATIONKEY=
SET INPUT_PROJECT_DIRECTORY=..\..\..\..\tests\force-di
SET INPUT_DEVHUB_ALIAS=devhub_acn
SET INPUT_WAIT_TIME=120
SET INPUT_ENABLE_COVERAGE=false
SET INPUT_ISVALIDATIONTOBESKIPPED=false
SET INPUT_SET_BUILD_NUMBER=false
SET INPUT_BUILD_ARTIFACT_ENABLED=false
SET INPUT_ISDIFFCHECK=true

ts-node ..\..\BuildTasks\CreateUnlockedPackageTask\CreateUnlockedPackage.ts