source 'https://rubygems.org'

gem 'jekyll', '>= 4.0.0'

group :jekyll_plugins do
  gem 'jekyll-feed', '0.12.0'
  gem 'jekyll-seo-tag', '2.6.1'
  gem 'jekyll-sitemap', '1.3.0'
  gem 'tzinfo-data'
end
